name: "Mel Lab @ Inha.Univ"
description: "This is the official web page for the Mel Lab at Inha.Univ."

url: "http://bellabHomepage.githun.io"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
